### ISSUE TITLE
Followed latest qwiklabs and pod would not start

### ISSUE THREAD

**Issue by sync** [GoogleCloudPlatform/gke-tracing-demo#52]
Runtime error somewhere in the code:

```
e "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/app/app.py", line 18, in <module>
    from google.cloud import pubsub_v1
  File "/usr/local/lib/python3.8/site-packages/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/usr/local/lib/python3.8/site-packages/google/cloud/pubsub_v1/types.py", line 20, in <module>
    from google.iam.v1 import iam_policy_pb2
  File "/usr/local/lib/python3.8/site-packages/google/iam/v1/iam_policy_pb2.py", line 17, in <module>
    from google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2

  File "/usr/local/lib/python3.8/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
SystemError: Objects/codeobject.c:131: bad argument to internal function
[2020-03-26 10:04:45 +0000] [9] [INFO] Worker exiting (pid: 9)
[2020-03-26 10:04:45 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
```

**Comment by nazimkedjar** [comment]
Same thing for me.
The pod is starting when I change the image 'gcr.io/pso-examples/tracing-demo:1.0.0' to another image in the terraform/tracing-demo-deployment.yaml file.
Could not finish the lab anyway.

**Comment by sync** [comment]
just noticed that the workshop is now in maintenance mode 👍

**Comment by daringcalf** [comment]
I finally got it to run and finished the lab.

Read the first few lines at https://github.com/daringcalf/gke-tracing-demo.git
